# Generated by Django 4.2.5 on 2023-09-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_description_todo_name_rename_title_todo_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='day',
            field=models.CharField(default='today', max_length=150),
        ),
    ]
